<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://mdwcorp.falabella.com/CORP/PE/OSB/wsdl/Listaempleados/Login/Validar-v1.0"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://mdwcorp.falabella.com/CORP/PE/OSB/wsdl/Listaempleados/Login/Validar-v1.0"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="P1001_ValidarLoginEmpleado">
        <plnk:role name="ListaempleadosLoginValidarPt">
            <plnk:portType name="tns:ListaempleadosLoginValidarPt"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://mdwcorp.falabella.com/CORP/PE/OSB/wsdl/Listaempleados/Login/Validar-v1.0"
         location="wsdl/CORP_PE_OSB_Listaempleados_Login_Validar.wsdl"/>
</wsdl:definitions>
