package pe.corp.xe.Listaempleados.opclcccws.runservice.ws;

import javax.xml.ws.WebFault;

@WebFault(faultBean="pe.corp.xe.Listaempleados.opclcccws.runservice.ws.Fault",
  targetNamespace="http://schemas.xmlsoap.org/soap/envelope/", name="Fault")
public class FaultMsg
  extends Exception
{
  private pe.corp.xe.Listaempleados.opclcccws.runservice.ws.Fault faultInfo;

  public FaultMsg(String message,
                  pe.corp.xe.Listaempleados.opclcccws.runservice.ws.Fault faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public FaultMsg(String message,
                  pe.corp.xe.Listaempleados.opclcccws.runservice.ws.Fault faultInfo,
                  Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public pe.corp.xe.Listaempleados.opclcccws.runservice.ws.Fault getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(pe.corp.xe.Listaempleados.opclcccws.runservice.ws.Fault faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)
