
---------------------
--  TABLA LOGIN : Esta tabla almacenara datos de usuarios que se crearan y que puedan ingresar al sistema
--  CAMPO ESTADO
--  1 --> ACTIVO
--  2 --> BLOQUEADO
--  3 --> CANCELADO
---------------------

CREATE TABLE SEGURIDAD.LOGIN(

ID_LOGIN VARCHAR2(10),
USUARIO VARCHAR2(20),
CLAVE VARCHAR2(20),
ESTADO NUMBER(1), 
CONSTRAINT LOGIN_ESTADO_CK CHECK (ESTADO BETWEEN 1 AND 3),
CONSTRAINT LOGIN_ID_PK PRIMARY KEY(ID_LOGIN),
CONSTRAINT LOGIN_USUARIO_UN UNIQUE(USUARIO)
);

/

ALTER INDEX SEGURIDAD.LOGIN_ID_PK RENAME TO LOGIN_ID_IDX;
ALTER INDEX SEGURIDAD.LOGIN_USUARIO_UN RENAME TO LOGIN_USUARIO_IDX;